use_frameworks!

target 'MBOpenWeather_Example' do
  pod 'MBOpenWeather', :path => '../'

  target 'MBOpenWeather_Tests' do
    inherit! :search_paths
    pod 'MBOpenWeather', :path => '../'

  end
end
