use_frameworks!

target 'MBOpenWeather_Example' do
  pod 'MBOpenWeather', :path => '../'

  target 'MBOpenWeather_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
